# Use postgres/example user/password credentials
version: '3.8'
services:
  db-dev:
    image: postgres:16.1
    ports:  
      - "5432:5432"
    restart: always
    environment:  
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root  
      POSTGRES_DB: natillera
    volumes:
      - /Users/SheilaC./Library/CloudStorage/GoogleDrive-sheilabermudz@gmail.com/Mi unidad/natillera/base_de_datos/postgresql/dev/data:/var/lib/postgresql/data
  db-pre:
    image: postgres:16.1
    ports:  
      - "5433:5432"
    restart: always
    environment:  
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root  
      POSTGRES_DB: natillera
    volumes:
      - /Users/SheilaC./Library/CloudStorage/GoogleDrive-sheilabermudz@gmail.com/Mi unidad/natillera/base_de_datos/postgresql/pre/data:/var/lib/postgresql/data
  db:
    image: postgres:16.1
    ports:  
      - "5434:5432"
    restart: always
    environment:  
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root  
      POSTGRES_DB: natillera
    volumes:
      - /Users/SheilaC./Library/CloudStorage/GoogleDrive-sheilabermudz@gmail.com/Mi unidad/natillera/base_de_datos/postgresql/pro/data:/var/lib/postgresql/data